name: Release

on:
  push:
    tags:
      - 'v*'
      - 'fishbone-*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --settings .github/maven-settings.xml deploy

      - name: Release using github cli
        run: gh release create ${GITHUB_REF##*/} ./target/*.jar -t "Release ${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
